phraseapp:
  project_id: "ff27c47569442cc984f4a9a522013c90"
  file_format: "json" 
  push:
    sources:
    - file: "./_locales/en/messages.json"
      params:
        locale_id: en
        update_translations: true

  pull:
    targets:
    - file: "./_locales/es/messages.json" 
      params:
        locale_id: es
    - file: "./_locales/fa/messages.json" 
      params:
        locale_id: fa
    - file: "./_locales/fr/messages.json" 
      params:
        locale_id: fr
    - file: "./_locales/nl/messages.json" 
      params:
        locale_id: nl
    - file: "./_locales/pt_PT/messages.json" 
      params:
        locale_id: pt_PT
    - file: "./_locales/ta/messages.json" 
      params:
        locale_id: ta
