phraseapp:
  project_id: "ff27c47569442cc984f4a9a522013c90"
  file_format: "json" 
  push:
    sources:
        update_translations: true
      - file: "./_locales/<locale_code>/messages.json"
  pull:
    targets:
      - file: "./_locales/<locale_code>/messages.json"
