phraseapp:
  access_token: "2eee0bce0d34b2a71200e8041fc119af4a9a3e21"
  project_id: "ff27c47569442cc984f4a9a522013c90"
  file_format: "json" 
  push:
    sources:
    - file: "./_locales/<locale_name>/messages.json"
  pull:
    targets:
    - file: "./_locales/<locale_name>/messages.json" 